Add RDS Snapshot Restore Script
cloudposse/rds-snapshot-restore pull request #1
Opened 2017-05-31 15:19 UTC by goruha

## What
* Script to do an in-place restore of RDS aurora cluster from snapshot with minimal downtime

## Why
* Restore databases from point-in-time backups

2017-05-31 15:23 UTC, osterman commented on rds_restore_cluster_from_snapshot.sh
> +MASTER_PASSWORD=$(MASTER_PASSWORD:-)
Wrong syntax. `${FOO:-}` (use curly braces, not `(` which means execution)

2017-05-31 15:24 UTC, goruha commented on rds_restore_cluster_from_snapshot.sh
> +MASTER_PASSWORD=$(MASTER_PASSWORD:-)
Right. 
I'm doing refactoring to reduce duplications

2017-05-31 15:24 UTC, osterman commented on rds_restore_cluster_from_snapshot.sh
> +if [ "$CLUSTER_JSON" == "" ]
`-z "${CLUSTER_JSON}"`

2017-05-31 15:25 UTC, osterman commented on rds_restore_cluster_from_snapshot.sh
> +echo "Cluster ${CLUSTER} have ${INSTANCES_COUNT} instances"
s/have/has/

2017-05-31 15:43 UTC, osterman commented on rds_restore_cluster_from_snapshot.sh
> +
Can you describe high-level how this works at the top in comments?
e.g. 

1. Record current database settings
2. Restore snapshot to temporary name
3. Rename live database
....

2017-05-31 15:45 UTC, osterman commented on rds_restore_cluster_from_snapshot.sh
> +####==================== Restoring cluster =================================#####
Can you wrap all these sections in functions and use comments like

```
#
# Restore cluster from snapshot
#
```

2017-06-15 17:43 UTC, osterman approved these changes
Nice refactoring

2017-06-15 17:45 UTC, osterman requested changes
s/not exists/does not exist/

2017-06-15 18:03 UTC, osterman approved these changes

2017-06-15 18:08 UTC, merged